### ISSUE TITLE
No echo

### ISSUE THREAD

**Issue by MarkSwanson** [khmarbaise/echo-maven-plugin#18]
How do I get this plugin to echo something to the screen?
Here's my config. I'm hoping to the "This message is ..." echo'd to the screen, but I do not no matter how I invoke maven.
Is there something else I need to do?
apache-maven 3.6.0

      <plugin>
            <groupId>com.soebes.maven.plugins</groupId>
            <artifactId>echo-maven-plugin</artifactId>
            <version>0.4.0</version>
            <executions>
                <execution>
                    <phase>initialize</phase>
                    <goals>
                        <goal>echo</goal>
                    </goals>
                    <configuration>
                        <echos>
                            <echo>This message is very early in the build process.</echo>
                        </echos>
                    </configuration>
                </execution>
            </executions>
        </plugin>

**Comment by khmarbaise** [comment]
Have you put the configuration into pluginManagement or outside?

**Comment by khmarbaise** [comment]
Unfortunately no feedback. If you have further information don't hesitate to open a new issue.
